site_name: CiÃªncia de Dados com ProgramaÃ§Ã£o DinÃ¢mica
theme:
  name: material
  logo: assets/logo.png
  features:
    - navigation.tabs
nav:
  # - InÃ­cio: index.md
  - ğŸ“Š VisualizaÃ§Ã£o de Dados:
    - viz/aula1.md
    - viz/aula2.md
